---
version: "2.0"
services:
  bark-small:
    image: alexpedersen/audio-akash:0.1.1
    expose:
      - port: 7860
        as: 7860
        to:
          - global: true
        # accept:
        #   - cars.ingress.europlots.com
    params:
      storage:
        data:
          mount: /mnt/
          readOnly: false
    env:
      - HF_HOME=/mnt/huggingface # Use persistent storage for model cache
      - OUTPUT_DIR=/mnt/output
      # - PUBLIC_URL=cars.ingress.europlots.com
profiles:
  compute:
    bark-small:
      resources:
        cpu:
          units: 6
        memory:
          size: 16Gi
        storage:
          - size: 4GB
          - name: data
            size: 40GB
            attributes:
              persistent: true
              class: beta3
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        bark-small:
          denom: uakt
          amount: 1000
deployment:
  bark-small:
    dcloud:
      profile: bark-small
      count: 1
